Update .openshift/action_hooks/stop

diff --git a/.openshift/action_hooks/stop b/.openshift/action_hooks/stop
--- a/.openshift/action_hooks/stop
+++ b/.openshift/action_hooks/stop
@@ -44,36 +44,38 @@ cd "$OPENSHIFT_REPO_DIR"
 #kill play if it was running
 if [[ -f "RUNNING_PID" ]]; then
 
-	echo "Stopping play application" >> $LOG_FILE
-	bash -c "$PLAY_COMMAND stop &>> $LOG_FILE" &> /dev/null
+        echo "Stopping play application" >> $LOG_FILE
+        echo "[exec] $PLAY_COMMAND stop" >> $LOG_FILE
+        $PLAY_COMMAND stop &>> $LOG_FILE
+        sleep 3
 
-	if [[ -f "RUNNING_PID" ]]; then
-		pid=`cat RUNNING_PID`
+        if [[ -f "RUNNING_PID" ]]; then
+                pid=`cat RUNNING_PID`
 
-		#try to kill it nicely
-		kill_app "kill -SIGTERM $pid"
+                #try to kill it nicely
+                kill_app "kill -SIGTERM $pid"
 
-		#try to kill it harshly
-		kill_app "kill -SIGKILL $pid"
-	fi
+                #try to kill it harshly
+                kill_app "kill -SIGKILL $pid"
+        fi
 fi
 
 #it survived, try to kill it manually
 if [[ -n `ps -A | grep java` ]]; then
-	#try to kill it nicely
-	kill_app "pkill -SIGTERM java"
+        #try to kill it nicely
+        kill_app "pkill -SIGTERM java"
 fi
 
 if [[ -n `ps -A | grep java` ]]; then
-	#try to kill it harshly
-	kill_app "pkill -SIGKILL java"
+        #try to kill it harshly
+        kill_app "pkill -SIGKILL java"
 fi
 
 #couldn't kill it
 if [[ -n `ps -A | grep java` ]]; then
-	echo "Error: could not stop play application, error executing 'pkill java'" >> $LOG_FILE
-	exit 1
+        echo "Error: could not stop play application, error executing 'pkill java'" >> $LOG_FILE
+        exit 1
 else
-	echo "[info] successfully stopped play application" >> $LOG_FILE
-	exit 0
+        echo "[info] successfully stopped play application" >> $LOG_FILE
+        exit 0
 fi
